### ISSUE TITLE
Peer to Peer Review 23.06.2020

### ISSUE THREAD

**Issue by mikethreels** [e71az/Enumerables#1]
# Hi Elias/Jessica,

You're doing a great job so far on the project, very smart to run as many tests as possible.
Maybe you can add below suggestions to your project as well.
- try using the to_enum method so the method returns an Enumerator when called without a block
- try keeping your methods as short as possible to avoid linter errors.

you are both doing great, keep up the good work.

with kind regard,
**team-122-the-manx**

**Comment by eliasecasta** [comment]
Thank you, Michael, we implemented your suggestions
