### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mimipeshy** [e71az/Enumerables#2]
Hi Elias,
Amazing progress you are making in your project and it is commendable. Something small to improve your code :computer_mouse: 

-  keep your test files separate from the main modules

- refactor your code to avoid repetition 

- Make use of regex expressions to make your modules smaller

All the best & Happy coding :computer:  :computer_mouse: 

KInd Regards, 
Peris Ndanu

**Comment by eliasecasta** [comment]
Thank you Peris, we applied your suggested changes
